name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Nikola
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --upgrade "Nikola[extras]==8.0.4"
      - name: Show Nikola Version
        run: nikola --version
      - name: Test push
        run: |
          echo "hello" > new_file.txt
          git config --global user.email "kleinerman@gmail.com"
          git config --global user.name "Ary Kleinerman"
          git add new_file.txt
          git commit -m "testing"
          git push origin master
      
